### ISSUE TITLE
channle样例使用过程中去掉 Producer函数 的co_await 10ms;会导致程序core掉 访问了无效的地址 

### ISSUE THREAD

**Issue by lossv** [bennyhuo/CppCoroutines#5]
Task<void, LooperExecutor> Producer(Channel<int> &channel) 改成  Task<void, NoopExecutor> Producer(Channel<int> &channel) 去掉 co_await 10ms会core掉

**Comment by bennyhuo** [comment]
我把 07 的 main 当中，Producer 改成 NoopExecutor，比且注释掉所有的 co_await xxms，程序是可以正常运行退出的。

issue 我先关闭了，如果方便，可以提供一下运行环境和完整复现的代码再重新打开哈。

顺便再提一下，这个项目本质上还是为了展示 C++ 协程的基本概念和使用方法，没有经过详细的测试，是不可以在生产环境中使用的哈。
