### ISSUE TITLE
05 使用如下调度器组合似乎一直等待

### ISSUE THREAD

**Issue by rickywei** [bennyhuo/CppCoroutines#8]
![image](https://github.com/user-attachments/assets/17a27ffc-b59c-427d-bd39-d4cf675faefc)

**Comment by bennyhuo** [comment]
是的，这个跟 AsyncExecutor 的实现有关系。future 的析构会阻塞 execute 函数退出，因此这里产生了一个死锁。

**Comment by rickywei** [comment]
@bennyhuo 请教下，我尝试把NewTrheadExecutor的detach改为join似乎也没有阻塞了，，，但是好像没想清楚原因；而且如果不用join时检测 -fsanitize=thread会报错

**Comment by bennyhuo** [comment]
不让用 detach 吗？

**Comment by rickywei** [comment]
> 不让用 detach 吗？

@bennyhuo 记忆中看报错好像会在detach的线程中用到被析构的Task的handle
